project:
  type: website
  output-dir: docs

website:
  title: "Curso_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Aulas"
        menu:
        - text: "Motivação"
          href: motivacao.qmd
        - text: "Revisão álgebra linear"
          href: revisao.qmd
        - text: "Análise de componentes principais"
          href: PCA.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

